import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
void main()=>runApp(const App());
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c)=>MaterialApp(debugShowCheckedModeBanner:false,title:'Baby Opportunity Finder',theme:ThemeData(useMaterial3:true,colorSchemeSeed:Colors.indigo),home:const Home());}
class Home extends StatefulWidget{const Home({super.key});@override State<Home> createState()=>_HomeState();}
class _HomeState extends State<Home>{
 int tab=0;final applied=<String>{};
 final jobs=[['Data Analyst / Business Analyst','Google Jobs','https://www.google.com/search?q=Data+Analyst+Business+Analyst+fresher+India+jobs'],['Data Quality / Data Operations','LinkedIn Jobs','https://www.linkedin.com/jobs/search/?keywords=Data%20Quality%20Data%20Operations%20Fresher&location=India'],['Implementation / ERP / CRM','Naukri','https://www.naukri.com/implementation-analyst-jobs-in-india'],['IT Support / NOC / Network','Indeed India','https://in.indeed.com/jobs?q=IT+Support+NOC+Network+Fresher&l=India'],['Startup fresher roles','Wellfound','https://wellfound.com/jobs']];
 Future<void> open(String s)async{final u=Uri.parse(s);if(await canLaunchUrl(u))await launchUrl(u,mode:LaunchMode.externalApplication);}
 @override Widget build(BuildContext c){final b=tab==0?_home():tab==1?_jobs():tab==2?_profile():_tracker();return Scaffold(appBar:AppBar(title:const Text('💗 Baby Opportunity Finder')),body:b,bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(x)=>setState(()=>tab=x),destinations:const[NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.work_outline),selectedIcon:Icon(Icons.work),label:'Jobs'),NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person),label:'Profile'),NavigationDestination(icon:Icon(Icons.checklist_outlined),selectedIcon:Icon(Icons.checklist),label:'Tracker')]));}
 Widget _home()=>ListView(padding:const EdgeInsets.all(18),children:[Text('Your job-search assistant',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:8),const Text('2026 E&TC fresher • India/Pune • low/no-code preferred • ₹3 LPA+ when disclosed.'),const SizedBox(height:18),_card('🔎 Find opportunities','Open targeted searches across job sources.',Icons.search,()=>setState(()=>tab=1)),_card('📄 Tailor CV','Get a truthful ATS-tailoring prompt.',Icons.description,_prompt),_card('🚫 Exclusions','Sales, BD, cold calling, telesales, field sales, commission-only and marketing excluded.',Icons.block,null),_card('📌 Track applications','Mark searches you have applied to.',Icons.checklist,()=>setState(()=>tab=3))]);
 Widget _jobs()=>ListView.builder(padding:const EdgeInsets.all(12),itemCount:jobs.length,itemBuilder:(c,i){final j=jobs[i];final d=applied.contains(j[0]);return Card(child:ListTile(leading:CircleAvatar(child:Text((i+1).toString())),title:Text(j[0]),subtitle:Text(j[1]),trailing:Wrap(spacing:2,children:[IconButton(icon:Icon(d?Icons.check_circle:Icons.check_circle_outline),onPressed:()=>setState(()=>d?applied.remove(j[0]):applied.add(j[0]))),IconButton(icon:const Icon(Icons.open_in_new),onPressed:()=>open(j[2]))])));});
 Widget _profile()=>ListView(padding:const EdgeInsets.all(18),children:[Text('Default profile',style:Theme.of(context).textTheme.headlineSmall),const ListTile(title:Text('Education'),subtitle:Text('B.E./B.Tech E&TC • 2026 fresher')),const ListTile(title:Text('Target roles'),subtitle:Text('Data Analyst, BA, Data Quality, Data Operations, MIS, Implementation, ERP/CRM, IT Support, NOC, Network Support, PMO')),const ListTile(title:Text('Preferences'),subtitle:Text('India/Pune • office roles • ₹3 LPA+ where disclosed')),const ListTile(title:Text('Exclude'),subtitle:Text('Sales, BD, cold calling, telesales, field sales, commission-only, marketing, senior roles, 2+ years'))]);
 Widget _tracker()=>ListView(padding:const EdgeInsets.all(18),children:[Text('Application tracker',style:Theme.of(context).textTheme.headlineSmall),const SizedBox(height:10),Text('Marked: '+applied.length.toString()),...applied.map((x)=>ListTile(leading:const Icon(Icons.check),title:Text(x)))]);
 Widget _card(String a,String b,IconData i,VoidCallback? f)=>Card(child:ListTile(leading:Icon(i),title:Text(a),subtitle:Text(b),onTap:f));
 void _prompt()=>showDialog(context:context,builder:(c)=>AlertDialog(title:const Text('CV tailoring prompt'),content:const SingleChildScrollView(child:Text('Compare my resume with this job description. Keep every claim truthful. Return matched keywords, missing learnable keywords, a one-page tailored resume, and a short application message. Never invent experience, salary, certification or employment history.')),actions:[TextButton(onPressed:()=>Navigator.pop(c),child:const Text('Close'))]));
}